name: 合并版本号
description: 在你对questionnaire.fix进行修改后并传入Operit AI插件市场，使用该模板对更新日志追加条目（同时合并到仓库）
title: "[Bug]: "
labels: ["pull request"]
name: 功能请求
about: 为这个项目提出一个想法
title: '[FEATURE] '
labels: 'enhancement'

body:
  - type: markdown
    attributes:
      value: "## 合并版本号"
  - type: markdown
    attributes:
      value: "> 在你对questionnaire.fix进行修改后并传入Operit AI插件市场，使用该模板对更新日志追加条目（同时合并到仓库）"
  - type: textarea
      attributes:
        label: 仓库地址
        description: 你需要提供你对修改版的开源仓库地址（不填则代表为默认OperitForge仓库）
  - type: textarea
      attributes:
        label: 版本号
        description: 你需要提供你发布的版本中的版本号，不填则代表默认使用发布版本号
  - type: textarea
      attributes:
        label: 更新日志（可写Markdown）
        description: 描在你的版本中的更新内容
      validations:
        required: true
